model:
  base_momentum: 0.99
  backbone:
    type: "resnet18"
    pretrained: false
  projection:
    type: "MLP"
    input_dim: 512
    hidden_dim: 512
    output_dim: 128
  predictor:
    type: "MLP"
    input_dim: 128
    hidden_dim: 512
    output_dim: 128

amp:
  sync_bn: True
  opt_level: "O1"

data:
  image_dir: "~/ImageNet-100_resized"
  resize_size: 224
  data_workers: 8
  train_batch_size: 512
  val_batch_size: 64
  dual_views: true
  num_examples: 126689

optimizer:
  type: lars
  base_lr: 0.3
  momentum: 0.9
  weight_decay: 1.0e-6
  total_epochs: 1200
  warmup_epochs: 10
  exclude_bias_and_bn: true

checkpoint:
  resume_path:
  save_epoch: 1
  ckpt_path: "ckpt/byol_imagenet/{}/{}_{}.pth.tar"

log:
  log_step: 10
  log_dir:

stage: "train"
distributed: true
